# Generated by Django 3.0.2 on 2020-03-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200318_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='initialized',
            field=models.BooleanField(default=False),
        ),
    ]
