# Generated by Django 3.0.2 on 2020-03-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_initialized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
