# Generated by Django 3.0.2 on 2020-03-28 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=-8223, max_length=12, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 123-456-7890.', regex='([0-9]{3}-){2}[0-9]{4}')]),
            preserve_default=False,
        ),
    ]
