# Generated by Django 3.0.2 on 2020-04-06 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_ask'),
        ('users', '0009_auto_20200330_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_client',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutor.Ask'),
        ),
    ]
