# Generated by Django 3.0.2 on 2020-04-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200413_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='num_ratings',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tutor_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
