# Generated by Django 3.0.2 on 2020-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200413_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tutor_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
