# Generated by Django 3.0.2 on 2020-04-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200419_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.TextField(blank=True, help_text='List any courses you feel comfortable tutoring.'),
        ),
    ]
