# Generated by Django 3.0.2 on 2020-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.TextField(blank=True, help_text='List any courses you feel comfortable tutoring for.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='Write a brief description of yourself. Be sure to include areas of strength for tutoring and any other information you would like other users to know.', verbose_name='bio'),
        ),
    ]
