# Generated by Django 3.0.2 on 2020-04-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_profile_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('comment_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.TextField(blank=True, help_text='List any courses you feel comfortable tutoring for.'),
        ),
    ]
