# Generated by Django 3.0.2 on 2020-04-22 17:51

from django.db import migrations


class Migration(migrations.Migration):
    """
    dependencies = [
        ('users', '0020_auto_20200421_2146'),
        ('users', '0017_auto_20200421_1350'),
    ]

    operations = [
    ]
    """
