language: python
python:
- 3.8.1
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: mojg1JTjl5AZffSn+heYwpIBe+Mqlk0u/ANChdcURYfCY7rXI0yyumaT3fswv5ikyrkWrtTtSVdGO2bkJdxIs/jubyOyMi1122K9Zd0FMkDfj+AtMAIwEd23Xe5alSZFPJe7XHg2H2VbDVn4wuBIyMiN5DLHwdGpBE2VECnmLUdK2tS90Q3M5+QbV/hDqJ4OLs++lOBm102OpLDnqk5DetMEGRF/UHPo1nvtSwwSkj7fjamhlYbnF1XKZ2zNt83Dnf2Cfv53AmHe2umz/zeMe7CFNNqXIeLSjYcx8KXSKGiBdILxrYZFw33VIqQfVRYezvAYlYuSHivSZRh9NEaacuGm7c2R+cQ6osOrgf9AuGHljcKSaoMRW0d2t2ND4agquctQ7gDCerzQ1Z8wyn2qUad6QUDHZhrtqGP/Is7xBf2FIf0Rk+vSbP9qR7aFHbSVVkDd2um15YnutWkzVn3J7I2UgkA8pZC+mVwU7XVcTSdAAuqY168QPceueR7J14gSVNQewj3NuKBY2lDiL3PSiETiceSvLIkYUiKT25kA+ralm7xvhXq+Tv4qjLssubn/QOqa+H3OGvxL7OA5Tvqhb0ttqpsv0akgAkbxyjKrE72Xa3mcQ2Ol8YXb8RLb4SR+8RJYGz1bH4P01uL5IR9NOI0l/Dl+pwDASq7iy0qe4vE=
  app: project-101-qt314
  on:
    repo: uva-cs3240-s20/project-101-qt314
