language: python
python:
- 3.8.1
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: FsATcVIYZjMJnsCI/gYJVtlTRRUYsjeqStHAQBVCJN9rSkHypO2wNobWzZAv3FCMtw80pwPS5fXh8GpIlY3cj/toRYeFjU1pB521pMDb93mqUAif5mEUQBd7wqVxD7EnzATlehSF6jbL5+2TH+HPL5J/Y1EbEiNYrEKqSYP3z+WEcAulzzxpzCngHCsp217idP3FskV9ZyOCK1NPP7Dzd0j6eRA06muBaBMGZhMHzbSA/F/AVtZFZvw+we+gGe4SgLoLkAwcK5ajnFW8H7dioh8ujr651ds6Rf1/K+BK9WPasQRnoubiTyws0xyushI9omTYma/qrXRGpraD2Q6eFo3PqYJmdlyUOpRLbTkt03YrrLRngIFxU0vG4oQ2hX88oldyLd3FmBDcwbofSRBTConirfzpjzsk/0kZbDkYFZK6UfWvCXG2rwL2afzy008Z2Rfdr8CCGY0jsXM0Kry02xnBqwSJteZkyx3CT6GYda+g+XE2vDHvfjPuNhUm6dwxfK+5KobbJHkyxaWJfLpR2DjeoRg2stfGOnCelAifqzXVRApsYTA0lowg3xG8y/yPJ+Jial/Ryk0YHaRAcxRHoz9xl7Nwo3yGucUgP3sGNCn6stmtvMCIqG9RN4sl4x+rqs5Du7BtxQ3QsH2Zk3J6W2Sfa5MOD+MK9yzF/4eiIYk=
  app: tutor
  on:
    repo: uva-cs3240-s20/project-101-qt314
