language: python
python:
- 3.8.1
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: ZbXdnIK923gT66uPQwYlZWcbpj2DVgBnzAnOeH7PqB6ug0YFf0zlpPFDc4HeFgVEuNq/u0iHTn1HS/uuuFaGiblWmHrb+MJJsnL+A4PSpVeLmCQYM72aHWOTEztWEdfCspiNw/OL9ZFJAR3Yq2PU5De014l8oxSruGJM6gEOG5CXCO+NloyC99knxJinzZ/UWMBFPBJiXNnXsB8UgCyuZ6UT0+SGxT5W6Q1/JCH8x78vk/JTqB7PQODva9g2MR5A9h0YD8gZqIBjFMgSPpxnMJpvFpmGOxP2XUH3hxTQvc4uGGKMcQgTWMgVK3GxipofKWgoyX6+P5plNatAkbNwcjwbq5SPJiZ2mryp7cpZJFVpz5YPHL2jnOeVHWKnw2QymsJACQG9tCnNnmvf0OfcBC8vshROVTSoSEZ4xMt64xmbsZZLkIRrBNahLKbOois+OSEJxv2FSgOvISabIDoSfCtiJgvP3e70jIeO+8FjmJ3irdzWGuuzbGZaHqG7d4KY01ljyY0w2jQMYOH7eNjbn+XjSUEZ9jEj669z83zbfMMDPW9YniQ1F23SWI9gMYnn0oUWEJHkg2G8op1OCKoDnYxL4hDT1OfjabXHUUucNEPSYgbRjotWNtI/GuoEcPzc6BMW7tN7a+iJ3cC4TEtWVxDFloz/5WM21NnScCapOFo=
  app: project-101-qt314
  on:
    repo: uva-cs3240-s20/project-101-qt314
