# Generated by Django 3.0.2 on 2020-02-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='profile',
            name='major2',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
