# Generated by Django 3.0.2 on 2020-03-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20200227_0759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
