# Generated by Django 3.0.2 on 2020-03-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='request',
        ),
    ]
