# Generated by Django 3.0.2 on 2020-03-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0007_delete_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fName', models.CharField(max_length=100)),
                ('lName', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=500)),
            ],
        ),
    ]
