# Generated by Django 3.0.2 on 2020-03-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request',
            new_name='Ask',
        ),
    ]
