# Generated by Django 3.0.2 on 2020-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20200330_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='question',
            field=models.TextField(),
        ),
    ]
