# Generated by Django 3.0.2 on 2020-04-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_auto_20200331_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ask',
        ),
    ]
