# Generated by Django 3.0.2 on 2020-04-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_ask'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
